const Workers = [

    {
        worker1: [1, "Thompson", "Anthony", "32", "M", "Head of Finance Dept", "17.01.2014"]
    },
    {
        worker2: [2, "Johnson", "Mary", "23", "F", "Software Engineer", "05.03.2019"]
    },
    {
        worker3: [3, "Chisom", "Oyeka", "28", "F", "Human Resources Manager", "21.06.2016"]
    },
    {
        worker4: [4, "Jide", "Olabisi", "29", "M", "Assitance Head(Softeware Dept)", "05.06.2016"]
    },
    {
        worker5: [5, "Williams", "Ajayi", "30", "M", "Head of Software Department", "06.09.2015"]
    },
    {
        worker6: [6, "Nancy", "Chukwuemeka", "27", "F", "Secretary", "23.08.2016"]
    },
    {
        worker7: [7, "Nicolas", "Uchenna", "26", "M", "Software Engineer", "22.02.2020"]
    },
    {
        worker8: [8, "Ahmed", "Olayinka", "24", "M", "Graphics Designer", "15.08.2020"]
    },
    {
        worker9: [9, "Halima", "Olayinka", "26", "F", "Senior Finance Manger", "30.05.2018"]
    },
    {
        worker10: [10, "Richard", "Adeniyi", "41", "M", "Chief Executive Office", "17.11.2010"]
    }

]

document.getElementById('A1').innerHTML = Workers[0].worker1[0]
document.getElementById('A2').innerHTML = Workers[0].worker1[1]
document.getElementById('A3').innerHTML = Workers[0].worker1[2]
document.getElementById('A4').innerHTML = Workers[0].worker1[3]
document.getElementById('A5').innerHTML = Workers[0].worker1[4]
document.getElementById('A6').innerHTML = Workers[0].worker1[5]
document.getElementById('A7').innerHTML = Workers[0].worker1[6]


document.getElementById('A8').innerHTML = Workers[1].worker2[0]
document.getElementById('A9').innerHTML = Workers[1].worker2[1]
document.getElementById('A10').innerHTML = Workers[1].worker2[2]
document.getElementById('A11').innerHTML = Workers[1].worker2[3]
document.getElementById('A12').innerHTML = Workers[1].worker2[4]
document.getElementById('A13').innerHTML = Workers[1].worker2[5]
document.getElementById('A14').innerHTML = Workers[1].worker2[6]


document.getElementById('A15').innerHTML = Workers[2].worker3[0]
document.getElementById('A16').innerHTML = Workers[2].worker3[1]
document.getElementById('A17').innerHTML = Workers[2].worker3[2]
document.getElementById('A18').innerHTML = Workers[2].worker3[3]
document.getElementById('A19').innerHTML = Workers[2].worker3[4]
document.getElementById('A20').innerHTML = Workers[2].worker3[5]
document.getElementById('A21').innerHTML = Workers[2].worker3[6]


document.getElementById('A22').innerHTML = Workers[3].worker4[0]
document.getElementById('A23').innerHTML = Workers[3].worker4[1]
document.getElementById('A24').innerHTML = Workers[3].worker4[2]
document.getElementById('A25').innerHTML = Workers[3].worker4[3]
document.getElementById('A26').innerHTML = Workers[3].worker4[4]
document.getElementById('A27').innerHTML = Workers[3].worker4[5]
document.getElementById('A28').innerHTML = Workers[3].worker4[6]



document.getElementById('A29').innerHTML = Workers[4].worker5[0]
document.getElementById('A30').innerHTML = Workers[4].worker5[1]
document.getElementById('A31').innerHTML = Workers[4].worker5[2]
document.getElementById('A32').innerHTML = Workers[4].worker5[3]
document.getElementById('A33').innerHTML = Workers[4].worker5[4]
document.getElementById('A34').innerHTML = Workers[4].worker5[5]
document.getElementById('A35').innerHTML = Workers[4].worker5[6]


document.getElementById('A36').innerHTML = Workers[5].worker6[0]
document.getElementById('A37').innerHTML = Workers[5].worker6[1]
document.getElementById('A38').innerHTML = Workers[5].worker6[2]
document.getElementById('A39').innerHTML = Workers[5].worker6[3]
document.getElementById('A40').innerHTML = Workers[5].worker6[4]
document.getElementById('A41').innerHTML = Workers[5].worker6[5]
document.getElementById('A42').innerHTML = Workers[5].worker6[6]


document.getElementById('A43').innerHTML = Workers[6].worker7[0]
document.getElementById('A44').innerHTML = Workers[6].worker7[1]
document.getElementById('A45').innerHTML = Workers[6].worker7[2]
document.getElementById('A46').innerHTML = Workers[6].worker7[3]
document.getElementById('A47').innerHTML = Workers[6].worker7[4]
document.getElementById('A48').innerHTML = Workers[6].worker7[5]
document.getElementById('A49').innerHTML = Workers[6].worker7[6]


document.getElementById('A50').innerHTML = Workers[7].worker8[0]
document.getElementById('A51').innerHTML = Workers[7].worker8[1]
document.getElementById('A52').innerHTML = Workers[7].worker8[2]
document.getElementById('A53').innerHTML = Workers[7].worker8[3]
document.getElementById('A54').innerHTML = Workers[7].worker8[4]
document.getElementById('A55').innerHTML = Workers[7].worker8[5]
document.getElementById('A56').innerHTML = Workers[7].worker8[6]


document.getElementById('A57').innerHTML = Workers[8].worker9[0]
document.getElementById('A58').innerHTML = Workers[8].worker9[1]
document.getElementById('A59').innerHTML = Workers[8].worker9[2]
document.getElementById('A60').innerHTML = Workers[8].worker9[3]
document.getElementById('A61').innerHTML = Workers[8].worker9[4]
document.getElementById('A62').innerHTML = Workers[8].worker9[5]
document.getElementById('A63').innerHTML = Workers[8].worker9[6]



document.getElementById('A64').innerHTML = Workers[9].worker10[0]
document.getElementById('A65').innerHTML = Workers[9].worker10[1]
document.getElementById('A66').innerHTML = Workers[9].worker10[2]
document.getElementById('A67').innerHTML = Workers[9].worker10[3]
document.getElementById('A68').innerHTML = Workers[9].worker10[4]
document.getElementById('A69').innerHTML = Workers[9].worker10[5]
document.getElementById('A70').innerHTML = Workers[9].worker10[6]







// STYLING AND MODIFYING THE TABLE WITH "DOM"

document.getElementById('Info-table').style.marginLeft = "24%"
document.getElementById('Info-table').style.marginTop = "1%"
document.getElementById('Info-table').style.backgroundColor = 'slateblue'
document.getElementById('Info-table').style.textAlign = 'center'
document.getElementById('Info-table').style.padding = '10px'
document.getElementById('Info-table').style.fontFamily = "Segoe UI"
document.getElementById('Info-table').style.fontSize = "16px"
document.getElementById('cooly').style.color = "blue"
document.getElementById('logo').style.marginLeft = "46%"
document.getElementById('logo').style.color = 'Blue'
document.getElementById('logo').style.paddingBottom = "50px"
document.getElementById('brooks').style.color="white"
document.getElementById('head4').style.backgroundColor='yellow'
